### ISSUE TITLE
Query: Allow search multiple group by name

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#117]
Now if we search multiple groups, the query page will search "GROUP1 OR GROUP2" in the second search.

The idea is to display data for each group separately.

**Comment by kyhoon** [comment]
![image](https://user-images.githubusercontent.com/30872891/158644670-65bf4911-c292-4e8a-9cf4-df138b193f9d.png)
(the outcome for searching "curve" first and then searching "maker" in the second search)

To me it seems like the current implementation already has this feature, or is this different from what you have intended?
For instance, perhaps you meant displaying "curve" and "maker" in separate tabs here instead of displaying them together in "curve or maker" tab

**Comment by magikadev** [comment]
I think displying seperately.

**Comment by magikadev** [comment]
Closing it, since current query is okay.

**Comment by rareweasel** [comment]
Closing issue. It is already implemented.
